// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LibertydemopetclinicTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchowner() {
    // Test name: search-owner
    // Step # | name | target | value
    // 1 | open | https://test3-petclinic-demo.liberty-test-cluster-7e2996fc95fd6eb4a4c7a63aa3e73699-0000.us-south.containers.appdomain.cloud/ | 
    driver.get("https://test3-petclinic-demo.liberty-test-cluster-7e2996fc95fd6eb4a4c7a63aa3e73699-0000.us-south.containers.appdomain.cloud/");
    // 2 | setWindowSize | 550x672 | 
    driver.manage().window().setSize(new Dimension(550, 672));
    // 3 | click | css=.navbar-toggler-icon | 
    driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
    // 4 | click | css=.nav-item:nth-child(2) span:nth-child(2) | 
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) span:nth-child(2)")).click();
    // 5 | click | id=lastName | 
    driver.findElement(By.id("lastName")).click();
    // 6 | type | id=lastName | Franklin
    driver.findElement(By.id("lastName")).sendKeys("Franklin");
    // 7 | click | css=.btn:nth-child(1) | 
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    // 8 | assertText | css=b | George Franklin
    assertThat(driver.findElement(By.cssSelector("b")).getText(), is("George Franklin"));
  }
  @Test
  public void addowner() {
    // Test name: add-owner
    // Step # | name | target | value
    // 1 | open | https://test3-petclinic-demo.liberty-test-cluster-7e2996fc95fd6eb4a4c7a63aa3e73699-0000.us-south.containers.appdomain.cloud/ | 
    driver.get("https://test3-petclinic-demo.liberty-test-cluster-7e2996fc95fd6eb4a4c7a63aa3e73699-0000.us-south.containers.appdomain.cloud/");
    // 2 | setWindowSize | 1295x687 | 
    driver.manage().window().setSize(new Dimension(1295, 687));
    // 3 | click | css=.nav-item:nth-child(2) span:nth-child(2) | 
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) span:nth-child(2)")).click();
    // 4 | click | linkText=Add Owner | 
    driver.findElement(By.linkText("Add Owner")).click();
    // 5 | click | id=firstName | 
    driver.findElement(By.id("firstName")).click();
    // 6 | type | id=firstName | garlapati
    driver.findElement(By.id("firstName")).sendKeys("garlapati");
    // 7 | type | id=lastName | mounisha
    driver.findElement(By.id("lastName")).sendKeys("mounisha");
    // 8 | type | id=address | abc
    driver.findElement(By.id("address")).sendKeys("abc");
    // 9 | type | id=city | blr
    driver.findElement(By.id("city")).sendKeys("blr");
    // 10 | type | id=telephone | 3456
    driver.findElement(By.id("telephone")).sendKeys("3456");
    // 11 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void editowner() {
    // Test name: edit-owner
    // Step # | name | target | value
    // 1 | open | https://test3-petclinic-demo.liberty-test-cluster-7e2996fc95fd6eb4a4c7a63aa3e73699-0000.us-south.containers.appdomain.cloud/ | 
    driver.get("https://test3-petclinic-demo.liberty-test-cluster-7e2996fc95fd6eb4a4c7a63aa3e73699-0000.us-south.containers.appdomain.cloud/");
    // 2 | setWindowSize | 550x672 | 
    driver.manage().window().setSize(new Dimension(550, 672));
    // 3 | click | css=.navbar-toggler-icon | 
    driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
    // 4 | click | css=.nav-item:nth-child(2) > .nav-link | 
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
    // 5 | click | css=.btn:nth-child(1) | 
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    // 6 | click | linkText=George Franklin | 
    driver.findElement(By.linkText("George Franklin")).click();
    // 7 | click | css=.btn:nth-child(3) | 
    driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
    // 8 | click | id=telephone | 
    driver.findElement(By.id("telephone")).click();
    // 9 | type | id=telephone | 345
    driver.findElement(By.id("telephone")).sendKeys("345");
    // 10 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void addnewpet() {
    // Test name: add-new-pet
    // Step # | name | target | value
    // 1 | open | https://test3-petclinic-demo.liberty-test-cluster-7e2996fc95fd6eb4a4c7a63aa3e73699-0000.us-south.containers.appdomain.cloud/ | 
    driver.get("https://test3-petclinic-demo.liberty-test-cluster-7e2996fc95fd6eb4a4c7a63aa3e73699-0000.us-south.containers.appdomain.cloud/");
    // 2 | setWindowSize | 550x672 | 
    driver.manage().window().setSize(new Dimension(550, 672));
    // 3 | click | css=.navbar-toggler-icon | 
    driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
    // 4 | click | css=.nav-item:nth-child(2) > .nav-link | 
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
    // 5 | click | css=.btn:nth-child(1) | 
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    // 6 | click | linkText=Eduardo Rodriquez | 
    driver.findElement(By.linkText("Eduardo Rodriquez")).click();
    // 7 | click | css=.btn:nth-child(4) | 
    driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
    // 8 | click | id=name | 
    driver.findElement(By.id("name")).click();
    // 9 | type | id=name | tom
    driver.findElement(By.id("name")).sendKeys("tom");
    // 10 | click | id=birthDate | 
    driver.findElement(By.id("birthDate")).click();
    // 11 | type | id=birthDate | 2023-02-01
    driver.findElement(By.id("birthDate")).sendKeys("2023-02-01");
    // 12 | mouseDownAt | id=type | -17,-314.66668701171875
    {
      WebElement element = driver.findElement(By.id("type"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 13 | mouseMoveAt | id=type | -17,-314.66668701171875
    {
      WebElement element = driver.findElement(By.id("type"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 14 | mouseUpAt | id=type | -17,-314.66668701171875
    {
      WebElement element = driver.findElement(By.id("type"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 15 | click | id=type | 
    driver.findElement(By.id("type")).click();
    // 16 | select | id=type | label=cat
    {
      WebElement dropdown = driver.findElement(By.id("type"));
      dropdown.findElement(By.xpath("//option[. = 'cat']")).click();
    }
    // 17 | click | css=option:nth-child(2) | 
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    // 18 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void editpet() {
    // Test name: edit-pet
    // Step # | name | target | value
    // 1 | open | https://test3-petclinic-demo.liberty-test-cluster-7e2996fc95fd6eb4a4c7a63aa3e73699-0000.us-south.containers.appdomain.cloud/ | 
    driver.get("https://test3-petclinic-demo.liberty-test-cluster-7e2996fc95fd6eb4a4c7a63aa3e73699-0000.us-south.containers.appdomain.cloud/");
    // 2 | setWindowSize | 550x672 | 
    driver.manage().window().setSize(new Dimension(550, 672));
    // 3 | click | css=.navbar-toggler | 
    driver.findElement(By.cssSelector(".navbar-toggler")).click();
    // 4 | click | css=.nav-item:nth-child(2) > .nav-link | 
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
    // 5 | click | css=.btn:nth-child(1) | 
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    // 6 | click | linkText=Eduardo Rodriquez | 
    driver.findElement(By.linkText("Eduardo Rodriquez")).click();
    // 7 | click | linkText=Edit Pet | 
    driver.findElement(By.linkText("Edit Pet")).click();
    // 8 | mouseDownAt | id=type | -17,-314.66668701171875
    {
      WebElement element = driver.findElement(By.id("type"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 9 | mouseMoveAt | id=type | -17,-314.66668701171875
    {
      WebElement element = driver.findElement(By.id("type"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 10 | mouseUpAt | id=type | -17,-314.66668701171875
    {
      WebElement element = driver.findElement(By.id("type"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 11 | click | id=type | 
    driver.findElement(By.id("type")).click();
    // 12 | select | id=type | label=cat
    {
      WebElement dropdown = driver.findElement(By.id("type"));
      dropdown.findElement(By.xpath("//option[. = 'cat']")).click();
    }
    // 13 | click | css=option:nth-child(2) | 
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    // 14 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void addvisit() {
    // Test name: add-visit
    // Step # | name | target | value
    // 1 | open | https://test3-petclinic-demo.liberty-test-cluster-7e2996fc95fd6eb4a4c7a63aa3e73699-0000.us-south.containers.appdomain.cloud/ | 
    driver.get("https://test3-petclinic-demo.liberty-test-cluster-7e2996fc95fd6eb4a4c7a63aa3e73699-0000.us-south.containers.appdomain.cloud/");
    // 2 | setWindowSize | 550x672 | 
    driver.manage().window().setSize(new Dimension(550, 672));
    // 3 | click | css=.navbar-toggler-icon | 
    driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
    // 4 | click | css=.nav-item:nth-child(2) span:nth-child(2) | 
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) span:nth-child(2)")).click();
    // 5 | click | css=.btn:nth-child(1) | 
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    // 6 | click | linkText=Betty Davis | 
    driver.findElement(By.linkText("Betty Davis")).click();
    // 7 | click | linkText=Add Visit | 
    driver.findElement(By.linkText("Add Visit")).click();
    // 8 | click | id=date | 
    driver.findElement(By.id("date")).click();
    // 9 | type | id=date | 2023-02-24
    driver.findElement(By.id("date")).sendKeys("2023-02-24");
    // 10 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
    // 11 | click | id=description | 
    driver.findElement(By.id("description")).click();
    // 12 | type | id=description | general-visit
    driver.findElement(By.id("description")).sendKeys("general-visit");
    // 13 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void listveterinarians() {
    // Test name: list-veterinarians
    // Step # | name | target | value
    // 1 | open | https://test3-petclinic-demo.liberty-test-cluster-7e2996fc95fd6eb4a4c7a63aa3e73699-0000.us-south.containers.appdomain.cloud/ | 
    driver.get("https://test3-petclinic-demo.liberty-test-cluster-7e2996fc95fd6eb4a4c7a63aa3e73699-0000.us-south.containers.appdomain.cloud/");
    // 2 | setWindowSize | 550x672 | 
    driver.manage().window().setSize(new Dimension(550, 672));
    // 3 | click | css=.navbar-toggler-icon | 
    driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
    // 4 | click | css=.nav-item:nth-child(3) span:nth-child(2) | 
    driver.findElement(By.cssSelector(".nav-item:nth-child(3) span:nth-child(2)")).click();
    // 5 | click | linkText=2 | 
    driver.findElement(By.linkText("2")).click();
  }
}
